export const RECORD_USER_TOKEN = 'SET_USER_TOKEN'
export const GET_USER_TOKEN = 'GET_USER_TOKEN'
export const SET_PAGE_DECLARE_LAW = 'SET_PAGE_DECLARE_LAW'
export const GET_PAGE_DECLARE_LAW = 'GET_PAGE_DECLARE_LAW'